# Generated by Django 4.2.5 on 2023-10-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_flashcardsets_flashcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
