# Generated by Django 4.2.5 on 2023-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
