# Generated by Django 4.2.5 on 2023-12-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
