# Generated by Django 4.2.5 on 2023-12-04 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
