# Generated by Django 4.2.5 on 2023-12-04 12:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default=users.models.generate_uuid, editable=False, max_length=50, unique=True),
        ),
    ]
