# Generated by Django 4.2.5 on 2023-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default='d6e765a2-d2c8-4a38-a57c-2d2f06e4f502', editable=False, max_length=50, unique=True),
        ),
    ]
