# Generated by Django 4.2.5 on 2023-12-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsets',
            name='shareKey',
        ),
    ]
