# Generated by Django 4.2.5 on 2023-12-05 01:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_flashcardsets_sharekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsets',
            name='shareKey',
            field=models.CharField(default=users.models.generate_uuid, max_length=50),
        ),
    ]
