# Generated by Django 4.2.5 on 2023-12-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_remove_flashcardsets_author_flashcardsets_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsets',
            name='access',
            field=models.ManyToManyField(related_name='setAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='flashcardsets',
            name='author',
        ),
        migrations.AddField(
            model_name='flashcardsets',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='setOwner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
