# Generated by Django 4.2.5 on 2023-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
